# Generated by Django 4.1.3 on 2022-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_codefile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
