# Generated by Django 4.1.3 on 2022-11-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_codefile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=15)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.codefile')),
            ],
        ),
    ]
