# Generated by Django 4.1.3 on 2022-11-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_codefile_private_codelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='link_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='CodeLink',
        ),
    ]
